'use client';

import { useState } from 'react';

interface Tag {
  id: string;
    product_name: string;
      price: number | null;
        unit: string;
          origin: string | null;
            category: string;
              is_active: boolean;
                expires_at: string;
                  drive_file_id?: string;
                  }
                  
                  interface TagCardProps {
                    tag: Tag;
                      onUpdate: () => void;
                      }
                      
                      export default function TagCard({ tag, onUpdate }: TagCardProps) {
                        const [updating, setUpdating] = useState(false);
                          const [price, setPrice] = useState(tag.price?.toString() || '');
                            const [isActive, setIsActive] = useState(tag.is_active);
                            
                              async function handleUpdate(e: React.FormEvent) {
                                  e.preventDefault();
                                      setUpdating(true);
                                          try {
                                                const res = await fetch(`/api/digital-tags/${tag.id}`, {
                                                        method: 'PATCH',
                                                                headers: { 'Content-Type': 'application/json' },
                                                                        body: JSON.stringify({
                                                                                  price: price === '' ? null : parseFloat(price),
                                                                                            is_active: isActive,
                                                                                                    }),
                                                                                                          });
                                                                                                                if (res.ok) {
                                                                                                                        onUpdate();
                                                                                                                                alert('Etiqueta actualizada correctamente');
                                                                                                                                      } else {
                                                                                                                                              alert('Error al actualizar etiqueta');
                                                                                                                                                    }
                                                                                                                                                        } catch (err) {
                                                                                                                                                              console.error(err);
                                                                                                                                                                    alert('Error de red');
                                                                                                                                                                        } finally {
                                                                                                                                                                              setUpdating(false);
                                                                                                                                                                                  }
                                                                                                                                                                                    }
                                                                                                                                                                                    
                                                                                                                                                                                    
                                                                                                                                                                                      return (
                                                                                                                                                                                          <div className="flex flex-col justify-between rounded-xl bg-white p-6 shadow-sm border border-gray-100 transition-all hover:shadow-md">
                                                                                                                                                                                                <div>
                                                                                                                                                                                                        <div className="flex items-center justify-between mb-4">
                                                                                                                                                                                                                  <span className="text-xs font-semibold px-2.5 py-0.5 rounded bg-gray-100 text-gray-800">
                                                                                                                                                                                                                              {tag.category}
                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                  <span className={`text-xs font-bold px-2.5 py-0.5 rounded text-white ${
                                                                                                                                                                                                                                                              isActive ? 'bg-green-600' : 'bg-red-600'
                                                                                                                                                                                                                                                                        }`}>
                                                                                                                                                                                                                                                                                    {isActive ? 'Activo' : 'Inactivo'}
                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                              <h3 className="text-lg font-bold text-gray-900 mb-1 line-clamp-2" title={tag.product_name}>
                                                                                                                                                                                                                                                                                                                        {tag.product_name}
                                                                                                                                                                                                                                                                                                                                </h3>
                                                                                                                                                                                                                                                                                                                                        <p className="text-xs text-gray-500 mb-4">
                                                                                                                                                                                                                                                                                                                                                  Origen: {tag.origin || 'Desconocido'} | Unidad: {tag.unit}
                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                  <form onSubmit={handleUpdate} className="space-y-4">
                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                        <label className="block text-xs font-semibold text-gray-600 mb-1">
                                                                                                                                                                                                                                                                                                                                                                                                      Precio (EUR)
                                                                                                                                                                                                                                                                                                                                                                                                                  </label>
                                                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                                                            type="number"
                                                                                                                                                                                                                                                                                                                                                                                                                                                          step="0.01"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={price}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setPrice(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="Sin precio"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="checkbox"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          id={`active-${tag.id}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        checked={isActive}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setIsActive(e.target.checked)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="h-4 w-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label htmlFor={`active-${tag.id}`} className="ml-2 text-sm text-gray-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Etiqueta Activa
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  disabled={updating}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className={`w-full rounded-lg py-2 text-sm font-semibold text-white shadow-sm transition-all ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            updating
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ? 'bg-blue-400 cursor-not-allowed'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            : 'bg-blue-600 hover:bg-blue-700 active:scale-95'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {updating ? 'Guardando...' : 'Guardar Cambios'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="mt-6 pt-4 border-t border-gray-100 text-[10px] text-gray-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>ID: {tag.id}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>Expira: {new Date(tag.expires_at).toLocaleDateString()}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
